### PR TITLE
Zone color customization

### PR DESCRIPTION
**Pull request by bfrymire**
* Update zone sprites to be white, allowing room instance `Colour` property and `image_blend` to effect draw color
* Increase zone *"pass through"* layer opacity to be more visible
* Add dotted line pattern for zone *"pass through"* layer

Runner_OXGfileoML

### CODE REVIEW

**Comment by jack27121** [comment]
are we able to set a default color? Like by default make them pink or red, or will it always be white by default

**Review by jack27121 — APPROVED** [review]

**Comment by bfrymire** [comment]
Apparently not. My original thought was to make a Variable Definition for the user can change per instance, but that doesn't update the color of the instance in the room editor. One of my goals for this change was to make it easier for the user to distinctly visualize the different zone areas within the room editor.

**Comment by jack27121** [comment]
> Apparently not. My original thought was to make a Variable Definition for the user can change per instance, but that doesn't update the color of the instance in the room editor. One of my goals for this change was to make it easier for the user to distinctly visualize the different zone areas within the room editor.

instance variables you can never see live in the room  editor. But if if you could set a default image_blend (color) that would work maybe?

Anything about color i'd use the color as opposed to an instance variable

**Comment by jack27121** [comment]
if not then im iffy about this. It's a nice feature but no one asked for it 🤷

**Comment by bfrymire** [comment]
In `master`, the user can still change the `Colour` of the instance in the room editor. The `Colour` will be blended with the fuchsia color of the sprite, which will look off, but allow each instance to be changed individually. To prevent the colors from looking off due to blending, the sprite had to be changed to white.

GameMaker_iE6QSN0WBd

But like you said, nobody asked for this, so it can be scrapped if you want.

**Comment by jack27121** [comment]
I know about the color blending, so i understand why it's white. Though i meant if it was possible to change this `colour`to be something other than white by default. But i don't think so. For now, i don't think we need to do this. I'll let you decide tho, can reopen at any time if we change our minds as well

**Pull request closed without merging**
